[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "XBZOXXK-HLB84002"
user = "frankdonatodiferdinando"
password = "ruzcuPzyzkuc5gitvy"
